language: python
python:
  - "3.6"
  - "3.7"


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage codecov
  - python setup.py install

# command to run tests
script:
  - coverage run -p sko/demo_func.py
  - coverage run -p examples/demo_ga.py
  - coverage run -p examples/demo_ga_tsp.py
  - coverage run -p examples/demo_ga_udf.py
  - coverage run -p examples/demo_ga_udf_tsp.py
  - coverage run -p examples/demo_pso.py
  - coverage run -p examples/demo_sa.py
  - coverage run -p examples/demo_sa_tsp.py examples/data/nctu.csv
  - coverage run -p examples/demo_aca_tsp.py
  - coverage run -p examples/demo_ia.py
  - coverage run -p examples/demo_afsa.py
  - coverage run -p examples/demo_pso_ani.py
  - coverage run -p examples/demo_de.py
  - coverage run -p examples/vrp.py

# Push the results back to codecov
after_success:
  - coverage combine
  - codecov